export const LOGIN_SUCCEED = "LOGIN_SUCCEED";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_WALL = "GET_WALL";
export const GET_MY_WALL = "GET_MY_WALL";

export const UPDATE_WALL = "UPDATE_WALL";
export const VOTE = "VOTE";

export const GET_ALL_PROFILES = "GET_ALL_PROFILES";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const GET_SURVEY = "GET_SURVEY";
export const GET_SURVEY_FAIL = "GET_SURVEY_FAIL";
export const GET_UPDATED_BOOL = "GET_UPDATED_BOOL";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

export const POST_CATEGORIES = "POST_CATEGORIES";
export const POST_CATEGORIES_FAIL = "POST_CATEGORIES_FAIL";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CATEGORIES_FAIL = "UPDATE_CATEGORIES_FAIL";

export const CREATE_NEW_TECH = "CREATE_NEW_TECH";
export const CREATE_NEW_TECH_FAIL = "CREATE_NEW_TECH_FAIL";

export const PUSH_NOTIFICATION = "PUSH_NOTIFICATION";
